### ISSUE TITLE
Getting an error building from source

### ISSUE THREAD

**Issue by rlgordey** [NewDayTechnology/benchmarkdotnet.analyser#15]
PS D:\Projects\benchmarkdotnet.analyser> .\build.ps1
Tool 'dotnet-stryker' (version '0.22.4') was restored. Available commands: dotnet-stryker
Tool 'fake-cli' (version '5.20.4') was restored. Available commands: fake
Tool 'dotnet-reportgenerator-globaltool' (version '4.8.8') was restored. Available commands: reportgenerator

Restore was successful.
The last restore is still up to date. Nothing left to do.
Ref:
Version: 0.1.0
Info Version: 0.1.0
run Package dotnet tool
Building project with version: LocalBuild
Shortened DependencyGraph for Target Package dotnet tool:
<== Package dotnet tool
   <== Stryker
      <== Consolidate code coverage
         <== Integration Tests
            <== Unit Tests
               <== Build
                  <== Restore
                     <== Clean

The running order is:
Group - 1
  - Clean
Group - 2
  - Restore
Group - 3
  - Build
Group - 4
  - Unit Tests
Group - 5
  - Integration Tests
Group - 6
  - Consolidate code coverage
Group - 7
  - Stryker
Group - 8
  - Package dotnet tool
Starting target 'Clean'
Finished (Success) 'Clean' in 00:00:00.0085726
Starting target 'Restore'
Starting task 'DotNet:restore': benchmarkdotnetanalyser.sln
D:\Projects\benchmarkdotnet.analyser> "C:\Program Files\dotnet\dotnet.EXE"  msbuild /version /nologo (In: false, Out: true, Err: true)
16.11.0.36601
D:\Projects\benchmarkdotnet.analyser> "C:\Program Files\dotnet\dotnet.EXE"  restore benchmarkdotnetanalyser.sln /nodeReuse:False "/bl:D:\Temp\tmp1E08.tmp.binlog" (In: false, Out: false, Err: false)
C:\Program Files\dotnet\sdk\5.0.400\MSBuild.dll -nologo -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\5.0.400\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\5.0.400\dotnet.dll -maxcpucount -target:Restore -verbosity:m /bl:D:\Temp\tmp1E08.tmp.binlog /nodeReuse:False benchmarkdotnetanalyser.sln
  Determining projects to restore...
  All projects are up-to-date for restore.
Finished (Failed) 'DotNet:restore' in 00:00:02.4887130
Finished (Failed) 'Restore' in 00:00:02.4929679

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target                      Duration
------                      --------
Clean                       00:00:00.0044772
Restore                     00:00:02.4924717   (Value cannot be null.
Parameter name: format)
Build                       00:00:00           (skipped)
Unit Tests                  00:00:00           (skipped)
Integration Tests           00:00:00           (skipped)
Consolidate code coverage   00:00:00           (skipped)
Stryker                     00:00:00           (skipped)
Package dotnet tool         00:00:00           (skipped)
Total:                      00:00:02.5892450
Status:                     Failure
---------------------------------------------------------------------
Script reported an error:
-> BuildFailedException: Target 'Restore' failed.
-> One or more errors occurred. (Value cannot be null.
   Parameter name: format)
-> ArgumentNullException: Value cannot be null.
   Parameter name: format
Hint: To further diagnose the problem you can run fake in verbose mode `fake -v run ...` or set the 'FAKE_DETAILED_ERRORS' environment variable to 'true'
Performance:
 - Cli parsing: 190 milliseconds
 - Packages: 57 milliseconds
 - Script analyzing: 19 milliseconds
 - Script running: 2 seconds
 - Script cleanup: 8 milliseconds
 - Runtime: 3 seconds
PS D:\Projects\benchmarkdotnet.analyser>

**Comment by tknightnd** [comment]
Thank you for raising the issue @rlgordey . Apologies for not getting back to you sooner, we'll investigate.

Many thanks!

**Comment by tknightnd** [comment]
Recreated locally with .Net sdk 5.0.401; with the same error as above.

**Comment by tknightnd** [comment]
Once again, thanks for the report @rlgordey .
