### ISSUE TITLE
Publish benchmarkdotnet.analyser to nuget.org

### ISSUE THREAD

**Issue by tomerrt** [NewDayTechnology/benchmarkdotnet.analyser#21]
**Is your feature request related to a problem? Please describe.**
Consuming packages from nuget is easier and more streamline. Also, the authentication method is easier.
**Describe the solution you'd like**
Similar to benchmarkdotnet which is published to nuget.org, can we have the tool published as nuget tool.

**Comment by tknightnd** [comment]
Apologies @tomerrt  for not seeing this earlier!  I entirely agree with you, moving to nuget. Please leave this with me.

**Comment by PixelByProxy** [comment]
Do you still have plans to do this?

**Comment by tknightnd** [comment]
Absolutely I do. Apologies for the progress on this @PixelByProxy @tomerrt, I need authorisations from our management on this issue.

**Comment by tknightnd** [comment]
Not forgotten, nor abandoned: we're looking to move forward with this request.

**Comment by tknightnd** [comment]
@PixelByProxy  @tomerrt  - after many, many months, this package is now on Nuget: https://www.nuget.org/packages/bdna/

**Comment by tknightnd** [comment]
Once again: apologies for the late delivery. We have some very stringent security gates to adhere to.
